### ISSUE TITLE
PDF Output: Creates PDF while collecting results.

### ISSUE THREAD

**Issue by kkrieger85** [DanielRuf/website-checks#27]
Cryptcheck.pdf => [HTTPS] Currently analysing kkrieger.de

httpobservatory => AWAITING SCANNER IN

SSL Labs => Checking. 

This is a complete check:

[webhint.pdf](https://github.com/DanielRuf/website-checks/files/3671339/webhint.pdf)
[webbkoll.pdf](https://github.com/DanielRuf/website-checks/files/3671340/webbkoll.pdf)
[ssllabs.pdf](https://github.com/DanielRuf/website-checks/files/3671341/ssllabs.pdf)
[ssldecoderfast-.pdf](https://github.com/DanielRuf/website-checks/files/3671342/ssldecoderfast-.pdf)
[securityheaders.pdf](https://github.com/DanielRuf/website-checks/files/3671344/securityheaders.pdf)
[psi-mobile.pdf](https://github.com/DanielRuf/website-checks/files/3671345/psi-mobile.pdf)
[psi-desktop.pdf](https://github.com/DanielRuf/website-checks/files/3671346/psi-desktop.pdf)
[lighthouse.pdf](https://github.com/DanielRuf/website-checks/files/3671348/lighthouse.pdf)
[httpobservatory.pdf](https://github.com/DanielRuf/website-checks/files/3671349/httpobservatory.pdf)
[hstspreload.pdf](https://github.com/DanielRuf/website-checks/files/3671350/hstspreload.pdf)
[cryptcheck.pdf](https://github.com/DanielRuf/website-checks/files/3671351/cryptcheck.pdf)
[crtsh.pdf](https://github.com/DanielRuf/website-checks/files/3671352/crtsh.pdf)

**Comment by DanielRuf** [comment]
Hi @kkrieger85,

can you explain in detail what the current issue is that you face?

**Comment by DanielRuf** [comment]
Hi @kkrieger85,

Can you provide more information about your environment like the NodeJS version and so on?

So far I could not reproduce this behaviour.

**Comment by DanielRuf** [comment]
I can currently only reproduce the SSLLabs one.

**Comment by kkrieger85** [comment]
npm -v                                                                                          
6.11.3

node -v                                                                                  
v12.10.0

docker -v                                                                                 
Docker version 18.09.7, build 2d0083d

website-checks 1.16.0

Internet 400M/cable
Maschine Dell XPS from 2019

**Comment by kkrieger85** [comment]
I ran this checks again. Now most of them are ok. 

I guess there is a delay due to DNS, not cached website data and so on.

**Comment by kkrieger85** [comment]
SSLLabs left incomplete

**Comment by DanielRuf** [comment]
Not DNS but they services which run the checks have cached the results now.

**Comment by DanielRuf** [comment]
Not DNS but the services which run the checks have cached the results now.

**Comment by DanielRuf** [comment]
This PR should fix the SSLLabs check:
https://github.com/DanielRuf/website-checks/pull/28

**Comment by DanielRuf** [comment]
Regarding CryptCheck, can you test with fresh / different domains which were not yet checked through this service?

https://github.com/DanielRuf/website-checks/pull/29

**Comment by kkrieger85** [comment]
Tested two domains with CryptCheck: one went fine, other has same result as mentioned above

**Comment by DanielRuf** [comment]
I will ask the owner if we can get a specific id or data-attribute for this

**Comment by DanielRuf** [comment]
I will ask the owner if we can get a specific id or data-attribute for this.

Which exact steps did you take?

**Comment by DanielRuf** [comment]
I will check HTTPObservatory later today.

**Comment by DanielRuf** [comment]
https://github.com/DanielRuf/website-checks/pull/30 should fix the HTTPObservatory check.

**Comment by kkrieger85** [comment]
My test step is: 'website-checks gaestehaus.saarland --output pdf' 

Yesterday I had a bad Wifi connection so I got some extra timeout errors: `[error] PageSpeed Insights TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded`

**Comment by DanielRuf** [comment]
Did you apply the changes to the globally instaled website-checks and test the PRs there or clone the repo for testing?

**Comment by DanielRuf** [comment]
Increasing the timeout more is not really a solution imo.

**Comment by kkrieger85** [comment]
I will clone this repo into a new folder and make checks again

**Comment by DanielRuf** [comment]
You can do it then on the provided branches with `node index.js domain --checkname`.

**Comment by DanielRuf** [comment]
You can test it then on the provided branches with `node index.js domain --checkname`.

**Comment by kkrieger85** [comment]
All checks on their branches are successfull. 

Thank you for your fast response and fixes.

**Comment by DanielRuf** [comment]
Thanks for the feedback. I will merge them.

I have also invited you as a contributor. https://github.com/DanielRuf/website-checks/invitations
