### ISSUE TITLE
PDF Output: Unwanted folder nesting

### ISSUE THREAD

**Issue by MyIsaak** [DanielRuf/website-checks#37]
The issue is when a user inputs a url that includes double forwardslash like

```
https://google.com
```
Which results to a `https:` folder with `google.com` folder nested within.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/4984415/67440113-1da7c080-f5f0-11e9-92e5-c29a2639b950.png)

**Comment by DanielRuf** [comment]
Hi @MyIsaak,

thanks for reporting this issue.

In general you should only provide `google.com`, the domain name =)

The docs might be not clear enaough.

I will create a patch to strip `https://` and `http://` from the input to prevent this.

**Comment by DanielRuf** [comment]
Hi @MyIsaak,

thanks for reporting this issue.

In general you should only provide `google.com`, the domain name =)

The docs might be not clear enough.

I will create a patch to strip `https://` and `http://` from the input to prevent this.

**Comment by lucas-barros** [comment]
@DanielRuf Can I work on this?

**Comment by lucas-barros** [comment]
What about slashes in the URL path? Should they be acceptable to create sub folders? 

Ex:
somedomain.com/path1
somedomain.com/path2
Folder structure:
somedomain.com
-- path1
-- path2

**Comment by DanielRuf** [comment]
The readme states that only a domain name should be supplied. So maybe Url.parse / new URL(...) makes more sense.

**Comment by DanielRuf** [comment]
> @DanielRuf Can I work on this?

Hi @lucas-barros, yes you can work on this.

The readme states that only a domain name should be supplied. So maybe Url.parse / new URL(...) makes more sense.

**Comment by DanielRuf** [comment]
Hi @lucas-barros,

It seems we already have a PR here: https://github.com/DanielRuf/website-checks/pull/38/files

**Comment by DanielRuf** [comment]
Hi @lucas-barros,

thanks for your interest to contribute to website-checks. I really appreciate it.

It seems we already have a PR here: https://github.com/DanielRuf/website-checks/pull/38
