### ISSUE TITLE
Create editorconfig file

### ISSUE THREAD

**Issue by DanielRuf** [DanielRuf/website-checks#41]
```
root = true

[*]
end_of_line = lf
insert_final_newline = false

[*.js]
indent_style = space
indent_size = 2
```

**Comment by faahim** [comment]
Hi @DanielRuf :wave: 
I'm going to take on this one! :slightly_smiling_face:

**Comment by DanielRuf** [comment]
Done in https://github.com/DanielRuf/website-checks/commit/3b97de94888ffa640cca3c9b0c0e64b1693794c4
