### ISSUE TITLE
SSL Labs Check multiple IPv4 AND IPv6

### ISSUE THREAD

**Issue by kkrieger85** [DanielRuf/website-checks#43]
It seems that the results/resultpage of SSLLabs.org is different if website to check has IPv4 AND IPv6

Then there is a overview site to select IPv4 vs. IPv6

URL Schema seems to be https://www.ssllabs.com/ssltest/analyze.html?d={{DOMAIN}}&s={{IPvX}}

If website to check has only IPv4 OR IPv6 then the test is still valid

**Comment by DanielRuf** [comment]
Can you provide an example? I thought https://github.com/DanielRuf/website-checks/blob/master/modules/checks/ssllabs.js#L13-L19 covers this too.

**Comment by DanielRuf** [comment]
Can you provide an example? I thought https://github.com/DanielRuf/website-checks/blob/master/modules/checks/ssllabs.js#L13-L19 covers this too.

Interesting that they have another markup there now.

**Comment by DanielRuf** [comment]
Can you provide an example? I thought https://github.com/DanielRuf/website-checks/blob/master/modules/checks/ssllabs.js#L11-L19 covers this too.

Interesting that they have another markup there now.

See **https://www.ssllabs.com/ssltest/analyze.html?d=daniel%2druf.de&hideResults=on&latest

**Comment by DanielRuf** [comment]
Can you provide an example? I thought https://github.com/DanielRuf/website-checks/blob/20da746321675e9dc6cbb0c0f99aafcce859b5d6/modules/checks/ssllabs.js#L11-L19 covers this too.

Interesting that they have another markup there now.

See **https://www.ssllabs.com/ssltest/analyze.html?d=daniel%2druf.de&hideResults=on&latest

**Comment by DanielRuf** [comment]
Can you provide an example? I thought https://github.com/DanielRuf/website-checks/blob/20da746321675e9dc6cbb0c0f99aafcce859b5d6/modules/checks/ssllabs.js#L11-L19 covers this too.

Interesting that they have another markup there now.

See https://www.ssllabs.com/ssltest/analyze.html?d=daniel%2druf.de&hideResults=on&latest

**Comment by kkrieger85** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=extremkleben.de&hideResults=on which has IPv4 AND IPv6 

vs 
https://www.ssllabs.com/ssltest/analyze.html?d=kkrieger.de which has only IPv4

**Comment by kkrieger85** [comment]
Hmm.. ok. Did a check with master-branch again and it created two pdf. wired

**Comment by DanielRuf** [comment]
How did you install website-checks? Keep in mind that I only publish the releases on GitHub (`DanielRuf/website-checks`).

**Comment by DanielRuf** [comment]
Feel free to reopen when you have this issue on master.
