### ISSUE TITLE
Why needs this cap_add: SYS_ADMIN?

### ISSUE THREAD

**Issue by supersexy** [DanielRuf/website-checks#48]
Why is this needed:

https://github.com/DanielRuf/website-checks/blob/5c51bb60e66444e8808daf8d389b2882eb01ffcc/docker-compose.yml#L9-L10

???

**Comment by DanielRuf** [comment]
@MyIsaak can you explain? =)

**Comment by MyIsaak** [comment]
cap stands for capabilities, so cap_add stands for adding capabilities. Since Linux 2.2, capabilities are another way of giving specific file access permissions to an unprivileged process. For example CAP_SYS_MODULE allows us to insert kernel modules. 

Since chromium's (used by puppeteer) sandboxing feature won't work without extra privileges, and still needs to be running with an unprivileged user, we allow for the SYS_ADMIN capability. As a result, the chromium is more secure due to sandboxing. Read more about their sandboxing here: https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md

**Comment by supersexy** [comment]
I really just want to know why this setting is needed in this project? 
From the [Docker Documentation](https://docs.docker.com/compose/compose-file/#cap_add-cap_drop) I know that this adds the [Linux capability](http://man7.org/linux/man-pages/man7/capabilities.7.html) SYS_ADMIN to the container, what is a _lot of things_:

```
CAP_SYS_ADMIN
              Note: this capability is overloaded; see Notes to kernel
              developers, below.

              * Perform a range of system administration operations
                including: quotactl(2), mount(2), umount(2), pivot_root(2),
                setdomainname(2);
              * perform privileged syslog(2) operations (since Linux 2.6.37,
                CAP_SYSLOG should be used to permit such operations);
              * perform VM86_REQUEST_IRQ vm86(2) command;
              * perform IPC_SET and IPC_RMID operations on arbitrary System
                V IPC objects;
              * override RLIMIT_NPROC resource limit;
              * perform operations on trusted and security Extended
                Attributes (see xattr(7));
              * use lookup_dcookie(2);
              * use ioprio_set(2) to assign IOPRIO_CLASS_RT and (before
                Linux 2.6.25) IOPRIO_CLASS_IDLE I/O scheduling classes;
              * forge PID when passing socket credentials via UNIX domain
                sockets;
              * exceed /proc/sys/fs/file-max, the system-wide limit on the
                number of open files, in system calls that open files (e.g.,
                accept(2), execve(2), open(2), pipe(2));
              * employ CLONE_* flags that create new namespaces with
                clone(2) and unshare(2) (but, since Linux 3.8, creating user
                namespaces does not require any capability);
              * call perf_event_open(2);
              * access privileged perf event information;
              * call setns(2) (requires CAP_SYS_ADMIN in the target
                namespace);
              * call fanotify_init(2);
              * call bpf(2);
              * perform privileged KEYCTL_CHOWN and KEYCTL_SETPERM keyctl(2)
                operations;
              * perform madvise(2) MADV_HWPOISON operation;
              * employ the TIOCSTI ioctl(2) to insert characters into the
                input queue of a terminal other than the caller's
                controlling terminal;
              * employ the obsolete nfsservctl(2) system call;
              * employ the obsolete bdflush(2) system call;
              * perform various privileged block-device ioctl(2) operations;
              * perform various privileged filesystem ioctl(2) operations;
              * perform privileged ioctl(2) operations on the /dev/random
                device (see random(4));
              * install a seccomp(2) filter without first having to set the
                no_new_privs thread attribute;
              * modify allow/deny rules for device control groups;
              * employ the ptrace(2) PTRACE_SECCOMP_GET_FILTER operation to
                dump tracee's seccomp filters;
              * employ the ptrace(2) PTRACE_SETOPTIONS operation to suspend
                the tracee's seccomp protections (i.e., the
                PTRACE_O_SUSPEND_SECCOMP flag);
              * perform administrative operations on many device drivers.
              * Modify autogroup nice values by writing to
                /proc/[pid]/autogroup (see sched(7)).
```

As we all know running random docker containers from the internet could be a big security risk, so I just want to know why a container with a set of tools that will check websites needs these system capabilities. I am really just curious - why is this needed?

BTW I like this set of tools very much, use some of these myself and just wanted to check if I might use this nice project, however I do not run random containers from the internet without taking a look at the contents before - nobody does that, right? ;)

**Comment by DanielRuf** [comment]
It is a recommended solution by developers working at Google.

See https://github.com/puppeteer/puppeteer/issues/809#issuecomment-331002207 and https://github.com/puppeteer/puppeteer/search?utf8=%E2%9C%93&q=sys_admin&type=

**Comment by supersexy** [comment]
Oups, somehow yesterday I did not see the answer of MyIsaak, that´s why I asked again - thanks for the info, interesting!
