### ISSUE TITLE
Webhint scrapper broken

### ISSUE THREAD

**Issue by myisaak** [DanielRuf/website-checks#76]
Fails with error:
```bash
[started] webhint
Error:  webhint Error: No node found for selector: #scanner-page-scan
Error:  webhint: Failed document written to /home/runner/work/website-checks/website-checks/iana.org/2021-10-15-09-19-09-045/webhint-failed.pdf
error Command failed with exit code 1.
```

![image](https://user-images.githubusercontent.com/4984415/137476234-d06f67a9-0629-406b-b362-f5185d550b39.png)

**Comment by tricinel** [comment]
@MyIsaak I took care of this in that PR. There's a small question that I had, so perhaps you can have a look and let me know what you think the best way is :)
